app:
  name: AInstitute-API

security:
  oauth2:
    resource:
      id: oauth2_application
      filter-order: 3
    access_token:
      validity_period: 3600
    refresh_token:
      validity_period: 10000

policy:
  json:
    filePath: /default-policy.json2

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  profiles:
    active: local

  datasource:
    url: jdbc:h2:~/ainstitute_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    hibernate:
        ddl-auto: create-drop

server:
  port: 8080