-- @formatter:off
-- --------- Delete Employee Data ------------------
DELETE FROM EMPLOYEE;

-- --------- Delete Institute and Members Data ------------------
DELETE FROM INSTITUTE_MEMBER_ROLE;
DELETE FROM INSTITUTE_MEMBER;
DELETE FROM INSTITUTE;

-- --------- Delete Login and User Data ------------------
DELETE FROM LOGIN_INFO;
DELETE FROM USER_INFO;

-- --------- Delete Reference Data ------------------
DELETE FROM PROVINCE;
DELETE FROM COUNTRY;
DELETE FROM TIME_ZONE;
DELETE FROM CURRENCY_TYPE;
DELETE FROM PAY_FREQUENCY;
DELETE FROM INSTITUTE_TYPE;
DELETE FROM ROLE_PERMISSION;
DELETE FROM PERMISSION;
DELETE FROM ROLE;
DELETE FROM PAYROLL_COMPONENT;
DELETE FROM PAYROLL_COMPONENT_TYPE;

-- --------- Insert Reference Data ------------------
INSERT INTO PAYROLL_COMPONENT_TYPE (CODE, NAME, CREATED_DATE, VERSION) VALUES ('BASIC', 'Basic', CURRENT_TIMESTAMP(),1), ('ALLOWANCE', 'Allowance', CURRENT_TIMESTAMP(), 1), ('TAX', 'Tax', CURRENT_TIMESTAMP(), 1);

INSERT INTO PAYROLL_COMPONENT (CODE, NAME, COMPONENT_TYPE_ID, CONTRIBUTION_TYPE, CREATED_DATE, VERSION) VALUES ('BASIC_SALARY', 'Basic Salary', 1, 'EARNING', CURRENT_TIMESTAMP(), 1), ('DEARNESS_ALLOWANCE', 'Dearness Allowance', 2, 'EARNING', CURRENT_TIMESTAMP(), 1), ('MEDICAL_ALLOWANCE', 'Medical Allowance', 2, 'EARNING', CURRENT_TIMESTAMP(), 1), ('HRA', 'House Rent Allowance', 2, 'EARNING', CURRENT_TIMESTAMP(), 1), ('CONVEYANCE_ALLOWANCE', 'House Rent Allowance', 2, 'EARNING', CURRENT_TIMESTAMP(), 1), ('SPECIAL_ALLOWANCE', 'Special Allowance', 2, 'EARNING', CURRENT_TIMESTAMP(), 1), ('LT_ALLOWANCE', 'Leave Travel ',2, 'EARNING', CURRENT_TIMESTAMP(), 1), ('PROVIDENT_FUND', 'Provident Fund', 2, 'DEDUCTION', CURRENT_TIMESTAMP(), 1), ('PROF_TAX', 'Professional tax', 3,'DEDUCTION', CURRENT_TIMESTAMP(), 1), ('INCOME_TAX', 'Income tax', 3, 'DEDUCTION', CURRENT_TIMESTAMP(), 1);

INSERT INTO ROLE (CODE, NAME, CREATED_DATE, VERSION) VALUES ('ADMIN', 'Admin', CURRENT_TIMESTAMP(), 1), ('INSTITUTE_ADMIN', 'Institute Admin', CURRENT_TIMESTAMP(), 1), ('HOD', 'Head of Department', CURRENT_TIMESTAMP(), 1), ('TEACHER', 'Teacher', CURRENT_TIMESTAMP(), 1), ('STUDENT', 'Student', CURRENT_TIMESTAMP(), 1), ('EMPLOYEE', 'Employee', CURRENT_TIMESTAMP(), 1);

INSERT INTO PERMISSION (CODE, NAME, CREATED_DATE, VERSION) VALUES ('VIEW_REF_DATA', 'VIEW_REF_DATA', CURRENT_TIMESTAMP(), 1), ('VIEW_EMPLOYEE', 'VIEW_EMPLOYEE', CURRENT_TIMESTAMP(), 1), ('VIEW_TEACHER', 'VIEW_TEACHER', CURRENT_TIMESTAMP(), 1), ('VIEW_STUDENT', 'VIEW_STUDENT', CURRENT_TIMESTAMP(), 1);

INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, STATUS, CREATED_DATE, STATUS_UPDATED_DATE, VERSION) VALUES (2, 1, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (2, 2, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (3, 3, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (3, 4, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (4, 4, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1);

INSERT INTO INSTITUTE_TYPE (CODE, NAME, CREATED_DATE, VERSION) VALUES ('SCHOOL', 'School', CURRENT_TIMESTAMP(), 1), ('COLLEGE', 'College', CURRENT_TIMESTAMP(), 1);

INSERT INTO PAY_FREQUENCY (CODE, NAME, CREATED_DATE, VERSION) VALUES ('YEARLY', 'Yearly', CURRENT_TIMESTAMP(), 1), ('MONTHLY', 'Monthly', CURRENT_TIMESTAMP(), 1), ('DAILY', 'Daily', CURRENT_TIMESTAMP(), 1), ('HOURLY', 'Hourly', CURRENT_TIMESTAMP(), 1);

INSERT INTO CURRENCY_TYPE (CODE, NAME, CREATED_DATE, VERSION) VALUES ('INR', 'Indian Rupee', CURRENT_TIMESTAMP(), 1);

INSERT INTO TIME_ZONE (CODE, NAME, OFFSET_VALUE, CREATED_DATE, VERSION) VALUES ('Asia/Kolkata', '(GMT+05:30) Asia/Kolkata', 19800, CURRENT_TIMESTAMP(), 1);

INSERT INTO COUNTRY (CODE, NAME, ISO_CODE, NUM_CODE, CREATED_DATE, VERSION) VALUES ('IN', 'INDIA', 'IND', 356,CURRENT_TIMESTAMP(), 1);

INSERT INTO PROVINCE (CODE, NAME, COUNTRY_ID, CREATED_DATE, VERSION) VALUES ('MP', 'Madhya Pradesh', 1,CURRENT_TIMESTAMP(), 1);

-- --------- Insert Login and User Data ------------------
INSERT INTO USER_INFO (USER_NAME, DISPLAY_NAME, EMAIL_ID, MOBILE_NO, CREATED_DATE, UPDATED_DATE, VERSION) VALUES('demo1', 'Demo User 1', 'demouser1@aschool.com', '1111111111', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1),('demo2', 'Test User 2', 'testuser2@aschool.com', '2222222222', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), ('demo3', 'Test User 3', 'testuser3@aschool.com','3333333333', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), ('demo4', 'Test User 4', 'testuser4@aschool.com', '4444444444', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1);

INSERT INTO LOGIN_INFO (USER_ID, PASSWORD, SECURITY_ANSWER, SECURITY_QUESTION, STATUS, STATUS_REASON, CREATED_DATE,LAST_LOGIN_DATE, PASSWORD_UPDATED_DATE, STATUS_UPDATED_DATE, VERSION) VALUES (1,'$2a$10$sBUvydqQCY4elPWlC3pIqeu920g0ifYWRpJug.gl671vkExk9E0dS', 'test_user1', 'test_user1', 'ACTIVE', 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (2, '$2a$10$sBUvydqQCY4elPWlC3pIqeu920g0ifYWRpJug.gl671vkExk9E0dS', 'test_user2', 'test_user2', 'ACTIVE', 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (3, '$2a$10$sBUvydqQCY4elPWlC3pIqeu920g0ifYWRpJug.gl671vkExk9E0dS', 'test_user3', 'test_user3', 'ACTIVE', 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1), (4, '$2a$10$sBUvydqQCY4elPWlC3pIqeu920g0ifYWRpJug.gl671vkExk9E0dS', 'test_user4', 'test_user4', 'ACTIVE', 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1);

-- --------- Insert Institute and Members Data ------------------
INSERT INTO INSTITUTE (CODE, INSTITUTE_TYPE_ID, NAME, CREATED_DATE, STATUS_UPDATED_DATE, UPDATED_DATE, STATUS, VERSION) VALUES ('INST1', 1, 'Institute 1', current_timestamp(), current_timestamp(), current_timestamp(), 'ACTIVE', 1), ('COLL1', 2, 'College 1', current_timestamp(), current_timestamp(), current_timestamp(), 'ACTIVE', 1);

INSERT INTO INSTITUTE_MEMBER (USER_ID, INSTITUTE_ID, STATUS, CREATED_DATE, STATUS_UPDATED_DATE, VERSION) VALUES (1, 1, 'ACTIVE', current_timestamp(), current_timestamp(), 1), (2, 2, 'ACTIVE', current_timestamp(), current_timestamp(), 1), (2, 1,'ACTIVE', current_timestamp(), current_timestamp(), 1), (1, 2, 'PENDING', current_timestamp(), current_timestamp(), 1), (3, 1, 'PENDING', current_timestamp(), current_timestamp(), 1), (3, 2, 'PENDING', current_timestamp(), current_timestamp(), 1);

INSERT INTO INSTITUTE_MEMBER_ROLE (INSTITUTE_MEMBER_ID, ROLE_ID, CREATED_DATE, STATUS_UPDATED_DATE, STATUS, VERSION)VALUES (1, 2, current_timestamp(), current_timestamp(), 'ACTIVE', 1), (1, 4, current_timestamp(), current_timestamp(), 'ACTIVE', 1), (2, 2, current_timestamp(), current_timestamp(), 'PENDING', 1), (2, 4, current_timestamp(), current_timestamp(), 'ACTIVE', 1), (3, 3, current_timestamp(), current_timestamp(), 'PENDING', 1), (3, 4, current_timestamp(), current_timestamp(), 'PENDING', 1), (4, 3, current_timestamp(), current_timestamp(), 'PENDING', 1), (4, 4, current_timestamp(), current_timestamp(), 'ACTIVE', 1), (5, 3, current_timestamp(), current_timestamp(), 'PENDING', 1), (6, 3, current_timestamp(), current_timestamp(), 'ACTIVE', 1);


-- @formatter:on