export const SET_LAYOUT_MODE = 'SET_LAYOUT_MODE';
export const SET_PROFILE_MODE = 'SET_PROFILE_MODE';
export const SET_LAYOUT_COMPACT = 'SET_LAYOUT_COMPACT';
export const SET_DARK_MENU = 'SET_DARK_MENU';

export const ON_MENU_CLICK = 'ON_MENU_CLICK';
export const ON_MENU_BUTTON_CLICK = 'ON_MENU_BUTTON_CLICK';
export const ON_TOPBAR_MENUBUTTON_CLICK = 'ON_TOPBAR_MENUBUTTON_CLICK';
export const ON_TOPBAR_ITEM_CLICK = 'ON_TOPBAR_ITEM_CLICK';
export const HIDE_OVERLAY_MENU = 'HIDE_OVERLAY_MENU';
export const SET_MENU_ACTIVE = 'SET_MENU_ACTIVE';
export const ON_RIGHT_PANEL_BUTTON_CLICK = 'ON_RIGHT_PANEL_BUTTON_CLICK';
export const ON_RIGHT_PANEL_CLICK = 'ON_RIGHT_PANEL_CLICK';
export const ON_DOCUMENT_CLICK = 'ON_DOCUMENT_CLICK';