export const todoActionTypes = {
    ADD_TODO: 'ADD_TODO',
    EDIT_TODO: 'EDIT_TODO',
    DELETE_TODO: 'DELETE_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    COMPLETE_ALL: 'COMPLETE_ALL',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED',
    RESET_WITH_TODOS: 'RESET_WITH_TODOS',
};
